In [3]:
import numpy as np

In [5]:
inputs = np.array([1,2])
inputs

array([1, 2])

In [6]:
weights = np.array([1,2])
weights

array([1, 2])

In [17]:
inputs < weights

array([False, False])

In [15]:
np.dot(inputs.T,weights)

5

In [12]:
iw = inputs*weights
iw.shape

(2,)

In [13]:
iws = 0
for i in iw:
    iws = iws +i
iws    

5

In [14]:
np.tanh(iws)

0.9999092042625951

In [16]:
x = 5
y = 6
if x<y:
    return x*y
else:
    return x/y

SyntaxError: 'return' outside function (<ipython-input-16-8551c6825099>, line 4)